name: Compile LaTeX

on:
  push:
    paths:
      - project-docs/project-proposal/**
      - .github/workflows/latex_build.yml

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile projectProposal.pdf
        uses: xu-cheng/latex-action@v4
        with:
          working_directory: project-docs/project-proposal
          root_file: projectProposal.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: projectProposal.pdf
          path: project-docs/project-proposal/projectProposal.pdf
